spring:
  application:
    name: default-config
    
eureka:
    instance:
      ip-address: true
    client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
          
